name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build APK and IPA
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version-file: pubspec.yaml

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk

    - name: Build IPA
      run: flutter build ios --release --no-codesign
